---
version: "0.2"

branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*:
    stage: pre-merge

models:
  - name: factorized blocks
  - Git: &git_pull_docker
      name: git pull
      repourl: "%(prop:git_reference)s"
      mode: full
      method: clobber
      shallow: false
      retryFetch: true
      haltOnFailure: true
  - Upload: &upload_artifacts
      source: artifacts
      timeout: 3600
      alwaysRun: true
  - ShellCommand: &get_deps
      name: "get dependencies"
      command: |
        set -xvue
        go get -v -t -d ./...
      timeout: 300  # 5 minutes
  - ShellCommand: &test
      name: "test & lint"
      command: |
        set -xvue
        make test
        make lint
      haltOnFailure: true
      timeout: 300  # 5 minutes
  - ShellCommand: &build
      name: "build"
      command: |
        set -xvue
        make
      haltOnFailure: true
      timeout: 300  # 5 minutes

stages:
  pre-merge:
    worker: &master-worker
      type: local

    steps:
      - TriggerStages:
          name: trigger compilation and test stages simultaneously
          stage_names:
            - centos8
          waitForFinish: true
          haltOnFailure: true
      #
      # Upload build status to artifacts
      #
      - ShellCommand:
          name: add successful .final_status to artifacts
          command: |
            mkdir -p build_status
            echo -n "SUCCESSFUL" > build_status/.final_status
          haltOnFailure: true
      - ShellCommand:
          name: add failed .final_status to artifacts if needed
          command: >
            [ -f build_status/.final_status ]
            || ( mkdir build_status &&
                 echo -n "FAILED" > build_status/.final_status )
          haltOnFailure: true
          alwaysRun: true
      - Upload:
          urls:
            - ["artifacts", ""]
          source: build_status
          alwaysRun: true

  centos8:
    name: "compile erasurecode for Centos Core (8.x)"
    worker: &build_worker_c8
      type: kube_pod
      path: eve/workers/worker.yml
      images:
        worker: eve/workers/compile_centos_8
    steps:
      - SetProperty:
          property: os_name
          value: centos8
          hideStepIf: true
      - Git: *git_pull_docker
      - ShellCommand: *get_deps
      - ShellCommand: *build
      - ShellCommand: *test
