name: Basic Tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'dependabot/**'
      - 'w/**'
      - 'q/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    container: rockylinux:9.0.20220720
    env:
      GOLINT_VERSION: 1.48.0
      GO_VERSION: 1.19
    steps:
      - run: dnf install -y git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/installation
      - name: install depss
        run: |
          set -xvue
          go get -v -t -d ./...
      - name: build
        run: |
          set -xvue
          make
      - name: test
        run: |
          set -xvue
          make test
          make lint

