name: Basic Tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'dependabot/**'
      - 'renovate/**'
      - 'w/**'
      - 'q/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    container: rockylinux:8.7
    env:
      GOLINT_VERSION: 1.21.0
      GO_VERSION: 1.15.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/installation
      - name: install depss
        run: |
          set -xvue
          go get -v -t -d ./...
      - name: build
        run: |
          set -xvue
          make
      - name: test
        run: |
          set -xvue
          make test
          make lint

